/* 노션 HR 연습 문제 */
-- 1번
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS 성명, LOWER(JOB_ID), DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE LOWER(LAST_NAME) = 'king';
    
    
-- 2번
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME, UPPER(JOB_ID), DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE UPPER(LAST_NAME) = 'KING';


-- 3번
SELECT DEPARTMENT_ID || ' ' || DEPARTMENT_NAME || ' ' || LOCATION_ID AS 부서정보
    FROM DEPARTMENTS;


-- 4번
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID, SALARY, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE SUBSTR(FIRST_NAME,1,1) > 'K' AND SUBSTR(FIRST_NAME,1,1) < 'Y'
    ORDER BY FIRST_NAME;


-- 5번
SELECT EMPLOYEE_ID, FIRST_NAME, LENGTH(FIRST_NAME || LAST_NAME) AS 이름길이, SALARY, LENGTH(SALARY) AS 급여자릿수
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 20;


-- 6번
SELECT FIRST_NAME, INSTR(FIRST_NAME, 'e', 1) AS "e의 위치"
    FROM EMPLOYEES;


-- 7번
SELECT FIRST_NAME, SALARY, MOD(SALARY, 30) AS 나머지
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 80;


-- 8번
SELECT FIRST_NAME, HIRE_DATE, 
        TRUNC((SYSDATE - HIRE_DATE)/7) || '주' || TRUNC(MOD((SYSDATE - HIRE_DATE),7)) || '일' AS "근무주/일"  
    FROM EMPLOYEES
    ORDER BY 2;


-- 9번
SELECT FIRST_NAME, SALARY, TO_CHAR(SALARY, '$999,999') AS 급여, DEPARTMENT_ID
    FROM EMPLOYEES
    WHERE DEPARTMENT_ID = 50;

