/* 2023년 2월 17일 SCOTT 연습문제(2) */
-- 1번
SELECT ENAME, HIREDATE, DEPTNO
    FROM EMP
    WHERE EMPNO = 7499;
    
-- 2번
SELECT *
    FROM EMP
    WHERE ENAME = 'ALLEN';

-- 3번
SELECT *
    FROM EMP
    WHERE ENAME > 'K';

-- 4번
SELECT ENAME, SAL, DEPTNO, HIREDATE
    FROM EMP
    WHERE HIREDATE > '81/4/2' AND HIREDATE < '82/12/9';

-- 5번
SELECT ENAME, JOB, SAL
    FROM EMP
    WHERE SAL > 1600 AND SAL < 3000;
    
-- 6번
SELECT *
    FROM EMP
    WHERE EXTRACT(YEAR FROM HIREDATE) != 1981;

SELECT *
    FROM EMP
    WHERE HIREDATE NOT BETWEEN '1981/01/01' AND '1981/12/12';

-- 7번
SELECT *
    FROM EMP
    WHERE JOB IN ('MANAGER', 'SALESMAN');
    
-- 8번
SELECT ENAME, EMPNO, DEPTNO
    FROM EMP
    WHERE NOT DEPTNO IN (20, 30);

-- 9번
SELECT EMPNO, ENAME, DEPTNO
    FROM EMP
    WHERE ENAME LIKE 'S%';
    
-- 10번
SELECT *
    FROM EMP
    WHERE ENAME LIKE '_A%';

-- 11번
SELECT *
    FROM EMP
    WHERE COMM IS NOT NULL;

-- 12번
SELECT *
    FROM EMP
    WHERE ENAME LIKE 'J%S';

-- 13번
SELECT *
    FROM EMP
    WHERE SAL >= 1500 AND DEPTNO = 30 AND JOB = 'MANAGER';

-- 14번
SELECT ENAME, SAL, NVL(COMM, 0), (SAL + NVL(COMM, 0)) AS 총액
    FROM EMP
    ORDER BY 4 DESC;

-- 15번
SELECT ENAME, SAL, SAL*1.13, DEPTNO
    FROM EMP
    WHERE DEPTNO = 10;

-- 16번
SELECT ENAME, HIREDATE, TO_CHAR(NEXT_DAY(HIREDATE + 60, '월'), 'YYYY/MM/DD') DDAY
    FROM EMP;
    
-- 17번
SELECT LOWER(SUBSTR(ENAME,1,3))
    FROM EMP
    WHERE LENGTH(ENAME) >= 6;

-- 18번
SELECT EMPNO, SAL, NVL(COMM, 0), ((NVL(COMM, 0)+SAL)*12) AS 연봉
    FROM EMP
    ORDER BY 연봉 DESC;

-- 19번
SELECT TO_CHAR(HIREDATE, 'YYYY"년"MM"월"DD"일"')
    FROM EMP;
    
-- 20번
SELECT ROUND(AVG(SAL), 2), MAX(SAL), MIN(SAL), COUNT(*)
    FROM EMP
    WHERE DEPTNO = 10;
    
-- 21번
SELECT *
    FROM EMP
    WHERE MOD(EMPNO, 2) = 0;
    
-- 22번
SELECT DEPTNO, JOB, COUNT(*)
    FROM EMP
    GROUP BY DEPTNO, JOB;

-- 23번
SELECT D.DEPTNO, DNAME, ENAME, SAL
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    ORDER BY D.DEPTNO;
    
-- 24번
SELECT D.DEPTNO, DNAME, ENAME, SAL
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE ENAME = 'ALLEN';

-- 25번
-- 서브 쿼리 이용
SELECT ENAME, DNAME, SAL, LOC
    FROM EMP E JOIN DEPT D
    ON E.DEPTNO = D.DEPTNO
    WHERE JOB = (SELECT JOB
                    FROM EMP
                    WHERE ENAME = 'ALLEN');

-- 26번
SELECT EMPNO, ENAME
    FROM EMP
    WHERE SAL > (SELECT AVG(SAL)
                        FROM EMP);
-- 27번
SELECT DEPTNO, AVG(SAL)
    FROM EMP
    GROUP BY DEPTNO
        HAVING AVG(SAL) < 2000;
    