/* 연습용 테이블 생성하기, 기존 테이블을 복사해서 사용 */
CREATE TABLE DEPT_TEMP
    AS SELECT * FROM DEPT;

SELECT * FROM DEPT_TEMP;
DROP TABLE DEPT_TEMP;

/* 테이블에 데이터를 추가하는 INSERT문 */
/*
 * INSERT INTO 테이블이름 (열1, 열2, ......) VALUES (열에 해당하는 데이터, ......);
 */
 
 /* 테이블에 데이터를 삽입(INSERT)하는 첫번째 방법 : 테이블 목록과 추가 할 값을 모두 표기하는 방법 */
INSERT INTO DEPT_TEMP(DEPTNO, DNAME, LOC) VALUES (50, 'DATABASE', 'SEOUL');
INSERT INTO DEPT_TEMP(LOC, DEPTNO) VALUES ('BUSAN', 60);

/* 테이블에 데이터를 삽입(INSERT)하는 두번째 방법 */
INSERT INTO DEPT_TEMP VALUES (70, 'DEVELOPER', 'SUWON');
INSERT INTO DEPT_TEMP VALUES (80, 'GUEST', 'INCHOEN'); 

/* 테이블에 NULL 데이터 입력하기 */
INSERT INTO DEPT_TEMP VALUES (90, 'WEB', NULL);
INSERT INTO DEPT_TEMP VALUES (91, 'MOBILE', '');
INSERT INTO DEPT_TEMP (DEPTNO, LOC) VALUES (92, 'ULSAN');

/* EMP TABLE만 복사, 내용은 복사 하지 않음 */
CREATE TABLE EMP_TEMP
    AS SELECT * FROM EMP
        WHERE 1 != 1;   -- 테이블을 복사하면서 데이터는 복사하고 싶지 않을 때 사용

SELECT * FROM EMP_TEMP;

/* 날짜 데이터는 '2020/01/01', '2020-01-01' 형식으로 입력 가능 
*  TO_DATE('2021/01/01', 'YYYY/MM/DD')로도 입력 가능
*/
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9001, '나영석', 'PRESIDENT', NULL, '2020/01/01', 9900, 1000, 10);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9002, '이영지', 'MANAGER', 9999, '2020/05/01', 7000, 500, 20);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9003, '안유진', 'MANAGER', 9999, '2020/07/01', 7000, 800, 30);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9004, '미미', 'MANAGER', 9999, '2023-05-01', 4500, 100, 40);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9005, '채원', 'MANAGER', 9999, TO_DATE('2021/02/01', 'YYYY/MM/DD'), 5500, 300, 40);
INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) VALUES (9006, '카즈하', 'MANAGER', 9999, SYSDATE, 7700, 300, 40);

/* 테이블에 있는 데이터 수정 하기 
*  UPDATE [변경할 테이블]
*  SET [변경할 열] = [변경할 데이터], ......
*  WHERE 조건
*/
SELECT * FROM DEPT_TEMP;

UPDATE DEPT_TEMP SET LOC = 'SEOUL';

UPDATE DEPT_TEMP 
    SET LOC = 'BUSAN'
    WHERE DNAME = 'WEB';

UPDATE DEPT_TEMP
    SET DNAME = 'ANDROID', LOC = 'DAEGU'
    WHERE DEPTNO = 60;

UPDATE DEPT_TEMP
    SET (DNAME, LOC) = (SELECT DNAME, LOC
                            FROM DEPT
                            WHERE DEPTNO = 40)
    WHERE DEPTNO = 40;

/* 테이블에 있는 데이터 삭제하기(DELETE) */
CREATE TABLE EMP_TEMP2 AS SELECT * FROM EMP;
SELECT * FROM EMP_TEMP2;

DELETE FROM EMP_TEMP2;
DROP TABLE EMP_TEMP2;

DELETE FROM EMP_TEMP2
    WHERE JOB = 'MANAGER';
    
/* 서브 쿼리를 사용하여 데이터 삭제하기 */
DELETE FROM EMP_TEMP2
    WHERE EMPNO IN (SELECT E.EMPNO
                        FROM EMP_TEMP2 E, SALGRADE S
                        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                        AND S.GRADE = 3
                        AND DEPTNO = 30);

/* 연습 문제 */
CREATE TABLE EX_EMP AS SELECT * FROM EMP;
CREATE TABLE EX_DEPT AS SELECT * FROM DEPT;
CREATE TABLE EX_SALGRADE AS SELECT * FROM SALGRADE;

-- 1. 
SELECT * FROM EX_DEPT;
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC) VALUES (50, 'ORACLE', 'BUSAN');
INSERT INTO EX_DEPT(DEPTNO, DNAME, LOC) VALUES (60, 'SQL', 'ILSAN');
INSERT INTO EX_DEPT VALUES (70, 'SELECT', 'INCHEON');
INSERT INTO EX_DEPT VALUES (80, 'DML', 'BUNDANG');

-- 2.
SELECT * FROM EX_EMP;
INSERT INTO EX_EMP VALUES(7201, 'TEST_USER1', 'MANAGER', 7788, '16/01/02', 4500,'',50);
INSERT INTO EX_EMP VALUES(7202, 'TEST_USER2', 'CLERK', 7201, '16/02/21', 1800,'',50);
INSERT INTO EX_EMP VALUES(7203, 'TEST_USER3', 'ANALYST', 7201, '16/04/11', 3400,'',60);
INSERT INTO EX_EMP VALUES(7204, 'TEST_USER4', 'SALESMAN', 7201, '16/05/31', 2700,300,60);
INSERT INTO EX_EMP VALUES(7205, 'TEST_USER5', 'CLERK', 7201, '16/07/20', 2600,'',70);
INSERT INTO EX_EMP VALUES(7206, 'TEST_USER6', 'CLERK', 7201, '16/09/08', 2600,'',70);
INSERT INTO EX_EMP VALUES(7207, 'TEST_USER7', 'LECTURER', 7201, '16/10/28', 2300,'',80);
INSERT INTO EX_EMP VALUES(7208, 'TEST_USER8', 'STUDENT', 7201, '18/03/09', 1200,'',80);

-- 3.
UPDATE EX_EMP
    SET DEPTNO = 70
    WHERE SAL > (SELECT AVG(SAL)
                    FROM EX_EMP
                    WHERE DEPTNO = 50);
SELECT * FROM EX_EMP
    ORDER BY DEPTNO;

-- 4.
UPDATE EX_EMP
 SET SAL = SAL * 1.1, DEPTNO = 80
 WHERE HIREDATE > (SELECT MIN(HIREDATE)
                    FROM EX_EMP
                    WHERE DEPTNO = 60);
SELECT * FROM EX_EMP
    ORDER BY DEPTNO;

-- 5. 
SELECT * FROM EX_SALGRADE;
DELETE FROM EX_EMP
    WHERE EMPNO IN (SELECT E.EMPNO
                    FROM EX_EMP E, EX_SALGRADE S
                    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
                    AND S.GRADE = 5);

SELECT * FROM EX_EMP
    ORDER BY DEPTNO;


